### ISSUE TITLE
1D dependency plots for cetegorical variables

### ISSUE THREAD

**Issue by SRFU-NN** [novonordisk-research/ProcessOptimizer#109]
Outer points can not be seen.

Don't interpolate between points

**Comment by SRFU-NN** [comment]
Box plots? Point and 1.96*std.dev.?

**Comment by dk-teknologisk-mon** [comment]
I'd like some feedback on possible ways to implement this fix (as I may have scope creep'd it a bit). I think we have a trade-off to make between "correctness" and "will the standard user make the right inference for the wrong reason".

I implemented a simple bar plot with a width of 1.96*std.dev to each side of the mean value, but then decided to try out illustrating the probability density for each category through the use of a graded color. I figured this would allow me to kill off explicitly showing the average function value, to discourge a common phenomenon where users tend to trick themselves into thinking of the average as the "true" value. Once I implemented the gradient, it was not terribly difficult to extend the same philosophy to _all_ of the 1D dependency plots, which resulted in plots like these:

![PO_probability_density_1D_prototype_1](https://user-images.githubusercontent.com/64902587/193672770-280ebd28-0ec0-45cb-ae2c-c7cfb7059dad.png)

I feel like the above works well for the categoric factor, but I'm pretty certain that "non-mathy" users will be very confused by what is going on in the right-hand side of e.g. the "Temperature" factor. In this case, it doesn't matter that it is technically much more correct than the old plot (with the data at hand, we have no clue how high temperature affects the outcome) - the user will simply give up on the plot because it's confusing. In the existing version of the plot, the less advanced users are usually able to quickly understand that the red area is "the uncertainty", even though they still make the error I mentioned above. A possible middle ground could be to hint at the upper/lower 2.5 % quantile limit that is used to define the 1D plots at present, like so:

![PO_probability_density_1D_prototype_2](https://user-images.githubusercontent.com/64902587/193674825-5d49c001-f6ec-479f-9d96-1996c8a8b01d.png)

This "fences in" the likely behavior of the system much more clearly and _probably_ preserves enough resemblence to plots that non-advanced users are used to seeing that it won't scare them off. I'd love to hear other thoughts on this though? I'll try asking a couple non-mathy people over the next couple of weeks for feedback, so we can get data that can prove me wrong :P

**Comment by SRFU-NN** [comment]
Would it make sense to use the colourmap for the dependence instead of just red? The vertical axes on the 1D plots are identical to the (implied) 3D axis on the 2D plots that are showed by colour.

But then we are showing uncertainty in two different ways: In the 2D maps, we show one value per parameter choice (the typical value), and “fade it out” according to the uncertainty, where for the 1D plots, we show all possible values, and then show how likely each is by “fading it out”. These are fundamentally different approaches of showing the probability distribution, and even though most users will not understand that (or perhaps even exactly because of that), it could confuse them.

Best regards
Søren Furbo
Automation Scientist
7660 Automation and Process Optimisation
+45 3079 0427 (direct) ǀ  ***@***.******@***.***>

**Comment by SRFU-NN** [comment]
Oh, and great work! I think the “fences” work great. They do tell in which area 95 % of the intensity is, which is an additional, valuable, and relevant piece of information, so I don’t even think we have a “correctness” issue there.

Best regards
Søren Furbo
Automation Scientist
7660 Automation and Process Optimisation
+45 3079 0427 (direct) ǀ  ***@***.******@***.***>

**Comment by dk-teknologisk-mon** [comment]
> Would it make sense to use the colourmap for the dependence instead of just red? The vertical axes on the 1D plots are identical to the (implied) 3D axis on the 2D plots that are showed by colour. 

I have been thinking a fair bit on this, and I cannot really come up with a good way to unite the color scales so it is consistent across the two types of plot. As you say, from the design of the graph forces us to display two different types of information in the different windows. I think this is the main source of potential confusion. The 1D dependency plots show the probability density "from above" with color to indicate, but for the 2D plots you are asking the figure to display a 3D density (probability density fog/cloud?) which I don't think we can solve.

> But then we are showing uncertainty in two different ways: In the 2D maps, we show one value per parameter choice (the typical value), and “fade it out” according to the uncertainty, where for the 1D plots, we show all possible values, and then show how likely each is by “fading it out”. These are fundamentally different approaches of showing the probability distribution, and even though most users will not understand that (or perhaps even exactly because of that), it could confuse them.

From a design perspective, I actually think it will be better if we split the plot up in two figures to avoid the confusion entirely. For instance a quick mock-up of how a pure 1D dependency figure could be designed is shown below. It would still need a colorbar with scale and a legend for the best observation plus "fences" defining the 95 % credibility interval.

![1D Figure mockup](https://user-images.githubusercontent.com/64902587/194233467-48bc2838-d1f2-4b69-abf6-5944d16fa0e5.png)

I think it works a lot better when the plot just needs to do one thing. I expect that the two-factor 2D plot would benefit from a similar treatment (including adding a legend to explain what all the dots mean...). I am also personally strongly in favor of hard-coding the figure text/explanation into the plots, so users don't have to look them up. If people don't want it, they can always crop the image in their PowerPoint presentations...

**Comment by dk-teknologisk-mon** [comment]
Back again after ambushing a few innocent bystanders with the mock-up above. 

The honest verdict thus far is that showing probability density as a shading really confuses people who could realistically be considered average users. I don't think the extra "correctness" in terms of how the model is displayed is worth it, since it gets in the way of the absolutely essential main point (where are we certain and where are we not). I will stick to removing the average function (the blue line in the old plot), but keep the uniform color between the "fences".
