### ISSUE TITLE
2D-partial dependence plots to use same color scale

### ISSUE THREAD

**Issue by dk-teknologisk-mon** [novonordisk-research/ProcessOptimizer#11]
By default, the 2D-partial dependence plots each use their own color scale, going from the lowest to the highest value that occurs in the plot. This is potentially misleading to the end user, as all factors will appear to have a significant effect when in practice this is not the case (as one might surmise from the 1D-partial dependence plots that are shown alongside).

**Comment by sqbl** [comment]
Correct. Thanks for reporting.
The current work-around is published in this [example](https://github.com/novonordisk-research/ProcessOptimizer/blob/develop/examples/7Dimensional_optimization_and_plotting.ipynb) (look at cell 10). 
A full and more permanent implementation would need a bit of coding to establish the min and max of the z-scale across all 2d plots and then set these values to the plotting function (it is actually already implemented like this in the Bokeh plot). Would you be willing to try to make a pull-request? I'll be happy to help you implement it in github and pip.

**Comment by AkselObdrup** [comment]
In the linked pull request I have updated plots.py. The function plot_objective now uses the same colorscale for all contour plots, the same scale for all 1d plots and a colorbar is displayed in the top right corner. Furthermore sampled points are shown with darkorange instead of black for improved visability.
