### ISSUE TITLE
Inconsistent requirements (bokeh)

### ISSUE THREAD

**Issue by dk-teknologisk-mon** [novonordisk-research/ProcessOptimizer#191]
I just had a colleague point out that environment solvers like Poetry do not "catch" that bokeh is a requirement with the way our repository is set up at the moment. I'm unsure whether this is caused by bokeh not being included in the `install_requires=['numpy', 'matplotlib', 'scipy',
                        'scikit-learn>=0.24.2', 'six', 'deap', 'pyYAML'],` inside setup.py (it is only listed under extras). At present I am unsure whether this is really a bug or expected behavior, so will investigate further.

**Comment by sqbl** [comment]
It is a left-over from the time in which Bokeh was a voluntary dependency. Back then, Bokeh was only used to do the o.g. bokeh_plot command. Bokeh_plot was our first example of an "interactive" visualization. It never really left the experimental stage - hence, Bokeh became a non-neccesary import (at versio 0.7.0).
Since then, Bokeh have been used to make a newer version of the pareto_plot. This is most likely more ready for publication than the old bokeh_plot - and I would therefore welcome a move of the Bokeh package to be a required package. 
(I actually thought that bokeh was made "mandatory" in version 0.7.6 - at least from reading the changelog. Perhaps, we should looke more into this.)

**Comment by sqbl** [comment]
I would basically revert this PR: https://github.com/novonordisk-research/ProcessOptimizer/commit/f7764713f0515b885fdb61d060abc413648f66be
Would that be ok? Also to remove the optional installation of Bokeh? Or should we teach user to treat Bokeh as optional? - the last might be done with a meaningfull warning in the two bokeh plotting functions

**Comment by dk-teknologisk-mon** [comment]
As far as I can see, reverting it should be sufficient. Since we plan on keeping and expanding on the Pareto plot (the main reason bokeh is used) I think it makes sense to make it a clear requirement.

**Comment by sqbl** [comment]
Will be closed
