### ISSUE TITLE
Convergence metrics/plottings

### ISSUE THREAD

**Issue by sqbl** [novonordisk-research/ProcessOptimizer#76]
We have a few plots to help the user in deciding whether to stop the experimentation or to continue in the search of an even better minimum. 
In the plot_expected_minimum_convergence (https://github.com/novonordisk-research/ProcessOptimizer/blob/a833b9bb9cd7fe6285cab3634919085ce884c032/ProcessOptimizer/plots.py#L912), we should likely remove the lower part of the plot or make it independent from input-features of little importance.
Explanation: The lower part of the plot, shows the euclidian distance between the last and the current "recipe" for the expected_minimum. In cases, where individual input-features have little or no effect on the expected_minimum, then a relatively large euclidian distance between two equally well performing minima will show up on the graph. This is unwanted behaviour.

Furthermore, let's sanity check that the euclidian distance is calculated in transformed space.

**Comment by dk-teknologisk-mon** [comment]
I think this issue is somewhat tied together with #121 in that to develop this functionality, we need to benchmark with known systems so we can actually answer:

1. What specifically defines "you have converged"? 
We need to answer this question anyway when we wish to tune our hyperparameters in order to optimize how fast PO "finds" (again, what does this mean?) the optimum in a system.
2. How do we reliably detect this state?
3. How do we communicate our beliefs/certainty about whether the system has converged?
