### ISSUE TITLE
Expected_minimum given a set of constraints

### ISSUE THREAD

**Issue by AkselObdrup** [novonordisk-research/ProcessOptimizer#80]
It would be useful to put a contraints flag on the expected_minimum function.

**Comment by dk-teknologisk-mon** [comment]
I am presently looking into constraints in order to allow users to work with mixtures (where a set of factors have to sum to say 1 kg). To my horror I have discovered that the implementation of constraints works by sampling random points in the chosen space, followed by a check of whether each point happens to obey the chosen constraint. As an example, say I have factors A and B, both with the limits [0, 10] and I want to constrain their sum to 10. The present functions only allow me to specify `A + B >= 10` and `A + B <= 10`, after which it begins happily drawing samples of A and B randomly in the hopes that they will satisfy both constraints - which will never happen for floats. 

You can of course hack this behavior by defining less strict equality, say `A + B >= 9.95` and `A + B <= 10.05`, but in this case the probability that a random point will obey the constraint is a measly 1 %. As soon as you have a bigger problem (which we usually do), the chance of finding a valid point falls off a cliff and you get no points back because it stops trying after 100k attempts if the success rate is less than 1/1000.

I'm going for an alternative implementation that identifies the valid subspace analytically instead. A sum constraint defines an N-1 dimensional plane through our N-dimensional space, and by looking at where this plane intersects the borders of the parameter space I can end up with a new set of factor limits and an equation that when sampled from only produces valid experiments from this subspace. I believe this kind of implementation will both allow us to get the n initial points we want in a spaced out manner that obeys the constraint as well as use EI to get the next point given the set of constraints.
